Task3
Simoffsky/BackendPractice pull request #3
Opened 2022-10-26 08:09 UTC by Simoffsky

2022-10-26 08:12 UTC, Dezzelshipc approved these changes

2022-10-26 11:39 UTC, Vixorem requested changes

2022-10-26 11:39 UTC, Vixorem commented on Domain/Services/AppointmentService.cs
> +	public Result<IEnumerable<Appointment>> GetFreeByDoctor(Doctor doctor) {
Свободные записи - это посути отсутствие записей. То есть аппойнтмент - это когда на какое то время есть запись. А ксли пе нет - это это как бы свободное время. По сути надо возвращать даты. Ну, например, с шагов 30минут. Ну или диапазон свободных окон. Ну тут основная суть в том, что возвращать надо никак не аппойнтмнт

2022-11-06 07:38 UTC, Vixorem approved these changes

2022-11-06 09:16 UTC, merged